import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './styles.css';

const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL||'https://pkggcyxsmgrzgvgwfpnv.supabase.co';
const SUPABASE_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_NiGMJs5gwHFoj75Nce53lA_81C-pG94';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const AREAS=[
 {slug:'personal',name:'شخصی',color:'#9C9B93'},
 {slug:'health',name:'سلامت',color:'#8FA99A'},
 {slug:'persuna',name:'Persuna',color:'#AD9486'},
 {slug:'finance',name:'مالی',color:'#AAA080'},
 {slug:'growth',name:'رشد',color:'#B9AA92'}
];
const NAV=[['today','امروز','Today'],['plan','برنامه','Plan'],['history','تاریخچه','History'],['review','مرور','Review'],['settings','تنظیمات','Settings']];
const fa=n=>Number(n||0).toLocaleString('fa-IR');
const dateKey=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran'}).format(new Date());
const formatDate=d=>new Intl.DateTimeFormat('fa-IR',{weekday:'long',year:'numeric',month:'long',day:'numeric',timeZone:'Asia/Tehran'}).format(new Date(d+'T12:00:00'));
const addDays=(date,n)=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran'}).format(d)};
const weekStart=date=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()-d.getDay());return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran'}).format(d)};
const areaFor=(areas,slug)=>areas.find(a=>a.slug===slug)||AREAS.find(a=>a.slug===slug)||AREAS[0];

function Auth({onUser}){
 const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(e){e.preventDefault();setBusy(true);setMessage('');const r=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setBusy(false);if(r.error)setMessage(r.error.message);else if(mode==='signup'&&!r.data.session)setMessage('حساب ساخته شد؛ ایمیلت را تأیید کن و سپس وارد شو.');else onUser(r.data.user)}
 return <div className="auth-screen"><div className="auth-glow"/><section className="auth-panel"><div className="brand-mark">MILO</div><span className="eyebrow">PERSONAL OPERATING PLANNER</span><h1>Today, intentionally.</h1><p>برنامه‌ریزی شخصی، با فضای کافی برای زندگی.</p><form onSubmit={submit}><input type="email" required placeholder="ایمیل" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required minLength="6" placeholder="رمز عبور" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy}>{busy?'در حال اتصال…':mode==='login'?'ورود':'ساخت حساب'}</button></form>{message&&<div className="auth-message">{message}</div>}<button className="text-button" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'ساخت حساب جدید':'ورود به حساب'}</button></section></div>
}

function State({type,onRetry}){
 const data={loading:['MILO','در حال آماده‌سازی فضای تو…'],error:['SYNC','اتصال به داده‌ها برقرار نشد.']};
 const x=data[type]||['EMPTY','چیزی برای نمایش نیست.'];
 return <div className="state"><span>{x[0]}</span><strong>{x[1]}</strong>{type==='error'&&<button onClick={onRetry}>تلاش دوباره</button>}</div>
}

function App({user}){
 const [page,setPage]=useState('today'),[tasks,setTasks]=useState([]),[goals,setGoals]=useState([]),[areas,setAreas]=useState([]),[focus,setFocus]=useState(''),[energy,setEnergy]=useState(6),[note,setNote]=useState(''),[date,setDate]=useState(dateKey()),[loading,setLoading]=useState(true),[error,setError]=useState(false),[toast,setToast]=useState(''),[taskTitle,setTaskTitle]=useState(''),[taskArea,setTaskArea]=useState('personal'),[priority,setPriority]=useState('medium'),[recurrence,setRecurrence]=useState(''),[reminder,setReminder]=useState(''),[editing,setEditing]=useState(null),[goalTitle,setGoalTitle]=useState('');
 const notify=x=>{setToast(x);window.clearTimeout(window.__miloToast);window.__miloToast=window.setTimeout(()=>setToast(''),1600)};
 async function ensureAreas(){const r=await supabase.from('areas').select('id,slug,name').eq('user_id',user.id).order('sort_order');if(r.error)throw r.error;if(r.data?.length)return r.data;const ins=await supabase.from('areas').insert(AREAS.map((a,i)=>({user_id:user.id,slug:a.slug,name:a.name,sort_order:i+1}))).select('id,slug,name').order('sort_order');if(ins.error)throw ins.error;return ins.data||[]}
 async function load(){setError(false);try{const a=await ensureAreas();const [t,g,f,l]=await Promise.all([supabase.from('tasks').select('*,area:areas(id,slug,name)').eq('user_id',user.id).order('due_date').order('created_at',{ascending:false}),supabase.from('goals').select('*').eq('user_id',user.id).order('created_at'),supabase.from('daily_focus').select('*').eq('user_id',user.id).eq('focus_date',date).maybeSingle(),supabase.from('daily_logs').select('*').eq('user_id',user.id).eq('log_date',date).maybeSingle()]);const bad=t.error||g.error||f.error||l.error;if(bad)throw bad;setAreas(a);setTasks(t.data||[]);setGoals(g.data||[]);setFocus(f.data?.title||'');setEnergy(l.data?.energy??6);setNote(l.data?.note||'');setLoading(false)}catch(_){setError(true);setLoading(false)}}
 useEffect(()=>{let alive=true;supabase.auth.getSession().then(({data})=>{if(alive&&data.session?.user){load()}else if(alive)setLoading(false)}).catch(()=>alive&&setLoading(false));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{if(s?.user)load()});return()=>{alive=false;subscription.unsubscribe()}},[]);
 useEffect(()=>{if(!loading&&page==='today')load()},[date]);
 useEffect(()=>{const ch=supabase.channel('milo-tasks').on('postgres_changes',{event:'*',schema:'public',table:'tasks',filter:`user_id=eq.${user.id}`},()=>load()).subscribe();return()=>{supabase.removeChannel(ch)}},[user.id]);
 const dayTasks=useMemo(()=>tasks.filter(t=>t.due_date===date&&t.status!=='cancelled'),[tasks,date]);
 const done=dayTasks.filter(t=>t.status==='done').length,total=dayTasks.length,pct=total?Math.round(done/total*100):0;
 async function saveTask(){if(!taskTitle.trim())return;const areaId=areaFor(areas,taskArea)?.id||null;const fields={title:taskTitle.trim(),area_id:areaId,priority,due_date:date,recurrence_rule:recurrence||null,reminder_at:reminder?new Date(reminder).toISOString():null};if(editing){const r=await supabase.from('tasks').update(fields).eq('id',editing).eq('user_id',user.id);if(r.error){notify('ذخیره انجام نشد');return}notify('کار ویرایش شد')}else{const r=await supabase.from('tasks').insert({user_id:user.id,...fields,status:'todo'}).select('*,area:areas(id,slug,name)').single();if(r.error){notify('ذخیره انجام نشد');return}setTasks(x=>[...x,r.data]);notify('کار اضافه شد')}setTaskTitle('');setEditing(null);setRecurrence('');setReminder('');await load()}
 async function toggleTask(t){const next=t.status==='done'?'todo':'done';const r=await supabase.from('tasks').update({status:next,completed_at:next==='done'?new Date().toISOString():null}).eq('id',t.id).eq('user_id',user.id);if(r.error){notify('ذخیره انجام نشد');return}await supabase.from('task_events').insert({user_id:user.id,task_id:t.id,event_type:next==='done'?'completed':'reopened',from_status:t.status,to_status:next,metadata:{source:'milo'}});if(next==='done'&&t.recurrence_rule){const nextDate=addDays(t.due_date||date,t.recurrence_rule==='weekly'?7:1);await supabase.from('tasks').insert({user_id:user.id,title:t.title,area_id:t.area_id,goal_id:t.goal_id,priority:t.priority,due_date:nextDate,status:'todo',recurrence_rule:t.recurrence_rule,sort_order:t.sort_order})}await load();notify(next==='done'?'بسته شد':'دوباره باز شد')}
 async function cancelTask(t){const r=await supabase.from('tasks').update({status:'cancelled'}).eq('id',t.id).eq('user_id',user.id);if(r.error){notify('ذخیره انجام نشد');return}setTasks(x=>x.filter(y=>y.id!==t.id));notify('کار حذف شد')}
 function editTask(t){setEditing(t.id);setTaskTitle(t.title);setTaskArea(t.area?.slug||areas.find(a=>a.id===t.area_id)?.slug||'personal');setPriority(t.priority||'medium');setDate(t.due_date||dateKey());setRecurrence(t.recurrence_rule||'');setReminder(t.reminder_at?new Date(t.reminder_at).toISOString().slice(0,16):'');setPage('today')}
 async function saveDaily(){const [f,l]=await Promise.all([supabase.from('daily_focus').upsert({user_id:user.id,focus_date:date,title:focus},{onConflict:'user_id,focus_date'}),supabase.from('daily_logs').upsert({user_id:user.id,log_date:date,energy,note},{onConflict:'user_id,log_date'})]);if(f.error||l.error)notify('ثبت روز انجام نشد');else notify('روز ثبت شد')}
 async function addGoal(){if(!goalTitle.trim())return;const r=await supabase.from('goals').insert({user_id:user.id,title:goalTitle.trim(),current_value:0,target_value:100,unit:'%',start_date:date}).select().single();if(r.error){notify('هدف ذخیره نشد');return}setGoals(x=>[...x,r.data]);setGoalTitle('');notify('هدف ساخته شد')}
 async function signout(){await supabase.auth.signOut()}
 return <div className="app"><header className="top-nav"><button className="wordmark" onClick={()=>setPage('today')}>MILO</button><nav>{NAV.map(n=><button key={n[0]} className={page===n[0]?'active':''} onClick={()=>setPage(n[0])}><span>{n[1]}</span><small>{n[2]}</small></button>)}</nav><div className="user-menu"><span>{(user.email||'M').slice(0,1).toUpperCase()}</span><button onClick={signout}>خروج</button></div></header>{loading?<State type="loading"/>:error?<State type="error" onRetry={load}/>:<><main>{page==='today'&&<Today date={date} setDate={setDate} focus={focus} setFocus={setFocus} energy={energy} setEnergy={setEnergy} note={note} setNote={setNote} tasks={dayTasks} pct={pct} done={done} areas={areas} taskTitle={taskTitle} setTaskTitle={setTaskTitle} taskArea={taskArea} setTaskArea={setTaskArea} priority={priority} setPriority={setPriority} recurrence={recurrence} setRecurrence={setRecurrence} reminder={reminder} setReminder={setReminder} editing={editing} saveTask={saveTask} toggleTask={toggleTask} cancelTask={cancelTask} editTask={editTask} saveDaily={saveDaily}/>} {page==='plan'&&<Plan date={date} setDate={setDate} tasks={tasks} goals={goals} goalTitle={goalTitle} setGoalTitle={setGoalTitle} addGoal={addGoal}/>} {page==='history'&&<History tasks={tasks}/>} {page==='review'&&<Review tasks={tasks}/>} {page==='settings'&&<Settings user={user}/>}</main></>}<nav className="mobile-nav">{NAV.map(n=><button key={n[0]} className={page===n[0]?'active':''} onClick={()=>setPage(n[0])}><span>{n[1]}</span><small>{n[2]}</small></button>)}</nav>{toast&&<div className="toast">{toast}</div>}</div>
}

function TaskRow({task,onToggle,onCancel,onEdit}){
 const area=task.area||AREAS.find(a=>a.slug===task.area_slug)||AREAS[0];
 return <div className={`task-row area-${area.slug||'personal'}`}><button className={`task-check ${task.status==='done'?'checked':''}`} onClick={()=>onToggle(task)}>{task.status==='done'?'✓':''}</button><div className="task-main"><b className={task.status==='done'?'completed':''}>{task.title}</b><span><i style={{background:area.color}}/>{area.name||'شخصی'}<em>·</em>{task.priority==='urgent'?'فوری':task.priority==='high'?'مهم':task.priority==='low'?'کم':'معمولی'}{task.recurrence_rule&&<><em>·</em>↻ {task.recurrence_rule==='weekly'?'هفتگی':'روزانه'}</>}</span></div><button className="row-edit" onClick={()=>onEdit(task)}>ویرایش</button><button className="row-delete" onClick={()=>onCancel(task)}>×</button></div>
}

function Today(p){
 const [filter,setFilter]=useState('all');
 const visible=p.tasks.filter(t=>filter==='all'||(filter==='open'&&t.status!=='done')||(filter==='done'&&t.status==='done'));
 const energyPct=p.energy*10;
 return <div className="page today-page"><div className="hero"><div><span className="eyebrow">MILO / TODAY</span><h1>امروز، با قصد.</h1><p>{formatDate(p.date)}</p></div><div className="hero-actions"><button className="pill" onClick={()=>p.setDate(dateKey())}>امروز</button><input className="date-input" type="date" value={p.date} onChange={e=>p.setDate(e.target.value)}/></div></div>
 <section className="ambient-stage"><div className="ambient-copy"><span>تمرکز امروز</span><h2>{p.focus||'یک چیز مهم را انتخاب کن.'}</h2><p>{p.focus?'همه‌چیز لازم نیست امروز اتفاق بیفتد.':'یک جمله بنویس تا روزت جهت بگیرد.'}</p></div><div className="energy-orb" style={{'--energy':energyPct+'%'}}><div className="halo"/><div className="orb-ring"><div className="orb-core"><strong>{fa(p.energy)}</strong><span>انرژی امروز</span></div></div><small>ENERGY / {fa(energyPct)}%</small></div><div className="ambient-shape shape-a"/><div className="ambient-shape shape-b"/></section>
 <section className="rhythm"><div><span>LIFE RHYTHM</span><b>امروز را سبک نگه دار.</b></div><div className="rhythm-orbs">{AREAS.slice(1,5).map(a=><i key={a.slug} style={{background:`radial-gradient(circle at 35% 30%,#fff, ${a.color} 45%, #333 100%)`}} title={a.name}/>)}</div><p>{fa(p.done)} از {fa(p.tasks.length)} کار بسته شده</p></section>
 <section className="quiet-stats"><div><span>کارهای امروز</span><strong>{fa(p.tasks.length)}</strong></div><div><span>انجام‌شده</span><strong>{fa(p.done)}</strong></div><div><span>پیشرفت</span><strong>{fa(p.pct)}٪</strong></div><div><span>انرژی</span><strong>{fa(p.energy)}</strong></div></section>
 <div className="content-grid"><section className="panel task-panel"><div className="panel-head"><div><span className="eyebrow">TODAY</span><h2>کارهای امروز</h2><p>{fa(p.done)} از {fa(p.tasks.length)} انجام شده</p></div></div>{p.editing&&<div className="edit-state">در حال ویرایش <button onClick={()=>{p.setTaskTitle('');p.setEditing(null);p.setRecurrence('');p.setReminder('');}}>لغو</button></div>}<div className="composer"><input value={p.taskTitle} onChange={e=>p.setTaskTitle(e.target.value)} onKeyDown={e=>e.key==='Enter'&&p.saveTask()} placeholder="کار بعدی را اضافه کن…"/><select value={p.taskArea} onChange={e=>p.setTaskArea(e.target.value)}>{AREAS.map(a=><option key={a.slug} value={a.slug}>{a.name}</option>)}</select><select value={p.priority} onChange={e=>p.setPriority(e.target.value)}><option value="low">کم</option><option value="medium">معمولی</option><option value="high">مهم</option><option value="urgent">فوری</option></select><select value={p.recurrence} onChange={e=>p.setRecurrence(e.target.value)}><option value="">بدون تکرار</option><option value="daily">روزانه</option><option value="weekly">هفتگی</option></select><button onClick={p.saveTask}>{p.editing?'ذخیره':'افزودن'}</button></div><div className="progress-line"><span>ریتم امروز</span><b>{fa(p.pct)}٪</b><i><em style={{width:p.pct+'%'}}/></i></div><div className="filters">{[['all','همه'],['open','باز'],['done','بسته']].map(x=><button key={x[0]} className={filter===x[0]?'active':''} onClick={()=>setFilter(x[0])}>{x[1]}</button>)}</div><div className="task-list">{visible.length?visible.map(t=><TaskRow key={t.id} task={t} onToggle={p.toggleTask} onCancel={p.cancelTask} onEdit={p.editTask}/>):<div className="empty">فعلاً چیزی اینجا نیست. اگر مهم است، ثبتش کن.</div>}</div></section>
 <aside className="panel today-space"><div className="panel-head"><div><span className="eyebrow">PERSONAL SPACE</span><h2>فضای امروز</h2><p>آرام نگهش دار.</p></div></div><label>جمله‌ی تمرکز<textarea value={p.focus} onChange={e=>p.setFocus(e.target.value)} placeholder="مهم‌ترین نتیجه‌ای که امروز می‌خواهم…"/></label><label>انرژی امروز <b>{fa(p.energy)} از ۱۰</b><input type="range" min="1" max="10" value={p.energy} onChange={e=>p.setEnergy(+e.target.value)}/></label><label>یادداشت پایان روز<textarea value={p.note} onChange={e=>p.setNote(e.target.value)} placeholder="چه چیزی خوب پیش رفت؟"/></label><label>یادآور<input className="date-input full" type="datetime-local" value={p.reminder} onChange={e=>p.setReminder(e.target.value)}/></label><button className="save-button" onClick={p.saveDaily}>ثبت روز</button></aside></div><div className="mantra">MILO <span>·</span> کمتر، اما کامل.</div></div>
}

function Plan({date,setDate,tasks,goals,goalTitle,setGoalTitle,addGoal}){
 const start=weekStart(date),days=Array.from({length:7},(_,i)=>addDays(start,i));
 return <div className="page"><div className="hero"><div><span className="eyebrow">MILO / PLAN</span><h1>هفته را شکل بده.</h1><p>هفته را قبل از اینکه هفته تو را هدایت کند، ببین.</p></div></div><section className="week-field">{days.map(d=><button key={d} className={d===date?'selected':''} onClick={()=>setDate(d)}><span>{new Intl.DateTimeFormat('fa-IR',{weekday:'short'}).format(new Date(d+'T12:00:00'))}</span><strong>{new Date(d+'T12:00:00').getDate().toLocaleString('fa-IR')}</strong><small>{fa(tasks.filter(t=>t.due_date===d&&t.status!=='cancelled').length)} کار</small><i/></button>)}</section><div className="plan-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">WEEK FLOW</span><h2>جریان هفته</h2></div></div>{tasks.filter(t=>t.due_date>=start&&t.due_date<=addDays(start,6)&&t.status!=='cancelled').sort((a,b)=>(a.due_date||'').localeCompare(b.due_date||'')).slice(0,12).map(t=><div className="plan-row" key={t.id}><div><b>{t.title}</b><span>{formatDate(t.due_date)}</span></div><strong>{t.status==='done'?'بسته':'باز'}</strong></div>)}{!tasks.some(t=>t.due_date>=start&&t.due_date<=addDays(start,6)&&t.status!=='cancelled')&&<div className="empty">این هفته هنوز چیزی شکل نگرفته.</div>}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">DIRECTION</span><h2>اهداف</h2><p>جهت، نه فشار.</p></div></div>{goals.map(g=>{const q=g.target_value?Math.min(100,Math.round(Number(g.current_value||0)/Number(g.target_value)*100)):0;return <div className="goal-row" key={g.id}><div><b>{g.title}</b><span>{g.description||'هدف فعال'}</span><i><em style={{width:q+'%'}}/></i></div><strong>{fa(q)}٪</strong></div>})}<div className="goal-add"><input value={goalTitle} onChange={e=>setGoalTitle(e.target.value)} placeholder="هدف جدید…"/><button onClick={addGoal}>افزودن</button></div></section></div><div className="mantra">SHAPE THE WEEK <span>·</span> جهت بده، نه فشار.</div></div>
}

function History({tasks}){
 const days=Array.from(new Set(tasks.map(t=>t.due_date).filter(Boolean))).sort().reverse().slice(0,30);
 return <div className="page"><div className="hero"><div><span className="eyebrow">MILO / HISTORY</span><h1>ریتمت را ببین.</h1><p>اثر واقعی اجرا را ببین، نه فقط فهرست کارها.</p></div></div><section className="history-field">{days.length?days.map(d=>{const list=tasks.filter(t=>t.due_date===d&&t.status!=='cancelled'),done=list.filter(t=>t.status==='done').length,p=list.length?Math.round(done/list.length*100):0;return <div className="history-row" key={d}><div className="history-date"><span>{new Intl.DateTimeFormat('fa-IR',{weekday:'short'}).format(new Date(d+'T12:00:00'))}</span><b>{new Date(d+'T12:00:00').getDate().toLocaleString('fa-IR')}</b></div><div className="history-pulse"><i style={{width:Math.max(p,3)+'%'}}/></div><div className="history-copy"><b>{fa(done)} از {fa(list.length)} کار</b><span>{formatDate(d)}</span></div><strong>{fa(p)}٪</strong></div>}):<div className="empty">تاریخچه هنوز شکل نگرفته.</div>}</section><div className="memory-strip"><span>MEMORY</span><b>به الگوها نگاه کن، نه فقط به نتیجه‌ها.</b></div></div>
}

function Review({tasks}){
 const days=Array.from({length:7},(_,i)=>addDays(dateKey(),i-6));
 const vals=days.map(d=>{const a=tasks.filter(t=>t.due_date===d&&t.status!=='cancelled');return a.length?Math.round(a.filter(t=>t.status==='done').length/a.length*100):0});
 const avg=Math.round(vals.reduce((a,b)=>a+b,0)/7);
 return <div className="page"><div className="hero"><div><span className="eyebrow">MILO / REVIEW</span><h1>چه چیزی کار می‌کند؟</h1><p>یک مکث کوتاه برای دیدن الگوی هفته.</p></div></div><section className="review-observatory"><div className="signal-field"><div className="signal-copy"><span>WEEKLY SIGNAL</span><strong>{fa(avg)}٪</strong><small>ریتم اجرای هفت روز اخیر</small></div><div className="signal-bars">{vals.map((v,i)=><div key={i}><i style={{height:Math.max(v,5)+'%'}}/><small>{new Intl.DateTimeFormat('fa-IR',{weekday:'short'}).format(new Date(days[i]+'T12:00:00'))}</small></div>)}</div></div><div className="steadiness"><div><strong>{fa(Math.max(0,Math.min(100,avg+12)))}</strong><span>STEADINESS</span></div></div></section><section className="reflection"><div><b>KEEP</b><span>چیزی که این هفته به آرامش جلو رفت را نگه دار.</span></div><div><b>CHANGE</b><span>فقط یک اصطکاک را برای هفته بعد کم کن.</span></div><div><b>NOTICE</b><span>کدام بخش زندگی بیشتر از ظرفیتش فضا گرفته است؟</span></div></section><div className="mantra">REFLECT, THEN CONTINUE <span>·</span> ادامه بده.</div></div>
}

function Settings({user}){
 return <div className="page settings-page"><div className="hero"><div><span className="eyebrow">MILO / SETTINGS</span><h1>فضای آرام تو.</h1><p>تنظیمات کم، کنترل روشن.</p></div></div><section className="settings-field"><div><span>حساب</span><b>{user.email}</b></div><div><span>منطقه زمانی</span><b>Asia / Tehran</b></div><div><span>ظاهر</span><b>Dark · Quiet Luxury</b></div><div><span>همگام‌سازی</span><b>Supabase · فعال</b></div><div><span>نسخه</span><b>MILO 1.0</b></div></section><div className="mantra">MILO <span>·</span> Today, intentionally.</div></div>
}

function Root(){
 const [user,setUser]=useState(null),[ready,setReady]=useState(false);
 useEffect(()=>{let active=true;supabase.auth.getSession().then(({data})=>{if(!active)return;setUser(data.session?.user||null);setReady(true)}).catch(()=>active&&setReady(true));const timer=setTimeout(()=>active&&setReady(true),3000);const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>active&&setUser(s?.user||null));return()=>{active=false;clearTimeout(timer);subscription.unsubscribe()}},[]);
 if(!ready)return <div className="boot">MILO</div>;
 return user?<App user={user}/>:<Auth onUser={setUser}/>;
}
createRoot(document.getElementById('root')).render(<Root/>);
