import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './styles.css';

const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const supabase=SUPABASE_URL&&SUPABASE_KEY?createClient(SUPABASE_URL,SUPABASE_KEY):null;
const areas=[['personal','شخصی'],['health','سلامت'],['persuna','Persuna'],['finance','مالی'],['growth','رشد']];
const nav=[['today','امروز','Today'],['plan','برنامه','Plan'],['history','تاریخچه','History'],['review','مرور','Review'],['settings','تنظیمات','Settings']];
const fa=n=>Number(n||0).toLocaleString('fa-IR');
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran'}).format(new Date());
const fmt=d=>new Intl.DateTimeFormat('fa-IR',{weekday:'long',year:'numeric',month:'long',day:'numeric',timeZone:'Asia/Tehran'}).format(new Date(d+'T12:00:00'));
const uid=()=>crypto.randomUUID();

function Auth({onUser}){const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function submit(e){e.preventDefault();if(!supabase){setMsg('اتصال Supabase تنظیم نشده است.');return}setBusy(true);setMsg('');let r=mode==='login'?await supabase.auth.signInWithPassword({email,password:pass}):await supabase.auth.signUp({email,password:pass});setBusy(false);if(r.error)setMsg(r.error.message);else if(mode==='signup'&&!r.data.session)setMsg('حساب ساخته شد؛ ایمیل را تأیید کن و سپس وارد شو.');else onUser(r.data.user)}
 return <div className="auth"><div className="auth-card"><div className="logo">MILO</div><div className="eyebrow">PERSONAL OPERATING PLANNER</div><h1>Today, intentionally.</h1><p>برنامه‌ریزی شخصی، ساده و دقیق.</p><form onSubmit={submit}><input type="email" required placeholder="ایمیل" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required minLength="6" placeholder="رمز عبور" value={pass} onChange={e=>setPass(e.target.value)}/><button disabled={busy}>{busy?'در حال اتصال…':mode==='login'?'ورود':'ساخت حساب'}</button></form>{msg&&<div className="message">{msg}</div>}<button className="link-btn" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'حساب ندارم':'حساب دارم'}</button></div></div>}

function App({user}){const [page,setPage]=useState('today'),[tasks,setTasks]=useState([]),[goals,setGoals]=useState([]),[areasData,setAreasData]=useState([]),[focus,setFocus]=useState(''),[energy,setEnergy]=useState(5),[note,setNote]=useState(''),[loading,setLoading]=useState(true),[task,setTask]=useState(''),[area,setArea]=useState('personal'),[priority,setPriority]=useState('medium'),[date,setDate]=useState(today()),[toast,setToast]=useState('');
 const show=x=>{setToast(x);setTimeout(()=>setToast(''),1600)};
 async function load(){setLoading(true);if(!supabase){setLoading(false);return}const [t,g,a,f,l]=await Promise.all([
  supabase.from('tasks').select('*').eq('user_id',user.id).order('due_date',{ascending:true}).order('created_at',{ascending:false}),
  supabase.from('goals').select('*').eq('user_id',user.id).order('created_at',{ascending:true}),
  supabase.from('areas').select('*').eq('user_id',user.id).order('created_at',{ascending:true}),
  supabase.from('daily_focus').select('*').eq('user_id',user.id).eq('focus_date',date).maybeSingle(),
  supabase.from('daily_logs').select('*').eq('user_id',user.id).eq('log_date',date).maybeSingle()
 ]);setTasks(t.data||[]);setGoals(g.data||[]);setAreasData(a.data||[]);setFocus(f.data?.focus_text||'');setEnergy(l.data?.energy||5);setNote(l.data?.notes||'');setLoading(false)}
 useEffect(()=>{load()},[date,user.id]);
 useEffect(()=>{const ch=supabase?.channel('milo-live').on('postgres_changes',{event:'*',schema:'public',table:'tasks',filter:`user_id=eq.${user.id}`},load).subscribe();return()=>{if(ch)supabase.removeChannel(ch)}},[user.id]);
 const dayTasks=useMemo(()=>tasks.filter(t=>t.due_date===date),[tasks,date]);
 const done=dayTasks.filter(t=>t.status==='done').length,total=dayTasks.length,pct=total?Math.round(done/total*100):0,open=dayTasks.filter(t=>t.status!=='done'&&t.status!=='cancelled').length;
 async function addTask(){if(!task.trim())return;const r=await supabase.from('tasks').insert({user_id:user.id,title:task.trim(),area_id:areasData.find(a=>a.slug===area)?.id||null,priority,due_date:date,status:'todo'});if(r.error)show(r.error.message);else{setTask('');show('کار اضافه شد');load()}}
 async function toggle(t){const status=t.status==='done'?'todo':'done';await supabase.from('tasks').update({status}).eq('id',t.id).eq('user_id',user.id);load()}
 async function remove(t){await supabase.from('tasks').update({status:'cancelled'}).eq('id',t.id).eq('user_id',user.id);show('کار حذف شد');load()}
 async function saveDaily(){await supabase.from('daily_focus').upsert({user_id:user.id,focus_date:date,focus_text:focus},{onConflict:'user_id,focus_date'});await supabase.from('daily_logs').upsert({user_id:user.id,log_date:date,energy,notes:note},{onConflict:'user_id,log_date'});show('امروز ذخیره شد')}
 async function signout(){await supabase.auth.signOut()}
 const title=nav.find(x=>x[0]===page)?.[1]||'امروز';
 return <div className="app"><aside className="sidebar"><div className="brand"><span>M</span><div><b>MILO</b><small>Personal Planner</small></div></div><nav>{nav.map(n=><button key={n[0]} className={page===n[0]?'active':''} onClick={()=>setPage(n[0])}><span>{n[1]}</span><small>{n[2]}</small></button>)}</nav><div className="side-bottom"><div className="user-dot">{(user.email||'M')[0].toUpperCase()}</div><div className="user-mail">{user.email}</div><button className="logout" onClick={signout}>خروج</button></div></aside>
 <main className="main"><header className="mobile-head"><button onClick={()=>setPage('today')}>MILO</button><span>{title}</span></header>
 {loading?<div className="loading">در حال بارگذاری…</div>:<>
 {page==='today'&&<Today date={date} setDate={setDate} focus={focus} setFocus={setFocus} energy={energy} setEnergy={setEnergy} note={note} setNote={setNote} tasks={dayTasks} pct={pct} open={open} done={done} task={task} setTask={setTask} area={area} setArea={setArea} priority={priority} setPriority={setPriority} addTask={addTask} toggle={toggle} remove={remove} saveDaily={saveDaily}/>}
 {page==='plan'&&<Plan tasks={tasks} goals={goals} areasData={areasData} date={date} setDate={setDate} setPage={setPage}/>}
 {page==='history'&&<History tasks={tasks}/>}
 {page==='review'&&<Review tasks={tasks}/>}
 {page==='settings'&&<Settings user={user}/>}
 </>}</main>{toast&&<div className="toast">{toast}</div>}</div>}

function TaskRow({t,toggle,remove}){return <div className="task-row"><button className={`check ${t.status==='done'?'checked':''}`} onClick={()=>toggle(t)}>{t.status==='done'?'✓':''}</button><div className="task-copy"><b>{t.title}</b><span>{t.priority==='urgent'?'فوری':t.priority==='high'?'مهم':t.priority==='low'?'کم‌اهمیت':'معمولی'}</span></div><button className="delete" onClick={()=>remove(t)}>×</button></div>}
function Today(p){return <div className="content"><div className="hero"><div><div className="eyebrow">MILO / TODAY</div><h1>امروز، با قصد.</h1><p>{fmt(p.date)}</p></div><div className="hero-actions"><button className="ghost" onClick={()=>p.setDate(today())}>امروز</button></div></div><div className="stats"><div><span>پیشرفت</span><strong>{fa(p.pct)}٪</strong></div><div><span>باز</span><strong>{fa(p.open)}</strong></div><div><span>انجام‌شده</span><strong>{fa(p.done)}</strong></div><div><span>انرژی</span><strong>{fa(p.energy)}/۱۰</strong></div></div>
 <div className="layout"><section className="panel"><div className="panel-head"><div><h2>کارهای امروز</h2><span>{fa(p.done)} از {fa(p.tasks.length)}</span></div></div><div className="composer"><input value={p.task} onChange={e=>p.setTask(e.target.value)} onKeyDown={e=>e.key==='Enter'&&p.addTask()} placeholder="کار بعدی را اضافه کن…"/><select value={p.area} onChange={e=>p.setArea(e.target.value)}>{areas.map(a=><option value={a[0]} key={a[0]}>{a[1]}</option>)}</select><select value={p.priority} onChange={e=>p.setPriority(e.target.value)}><option value="low">کم</option><option value="medium">معمولی</option><option value="high">مهم</option><option value="urgent">فوری</option></select><button onClick={p.addTask}>افزودن</button></div><div className="progress"><div><span>پیشرفت امروز</span><b>{fa(p.pct)}٪</b></div><i><em style={{width:p.pct+'%'}}/></i></div><div className="task-list">{p.tasks.length?p.tasks.map(t=><TaskRow key={t.id} t={t} toggle={p.toggle} remove={p.remove}/>):<div className="empty">برای امروز چیزی ثبت نشده.</div>}</div></section>
 <aside className="panel side-panel"><div className="panel-head"><div><h2>تمرکز امروز</h2><span>یک جمله کافی است</span></div></div><textarea value={p.focus} onChange={e=>p.setFocus(e.target.value)} placeholder="مهم‌ترین نتیجه‌ای که امروز می‌خواهم…"/><div className="field"><label>انرژی امروز <b>{fa(p.energy)} از ۱۰</b></label><input type="range" min="1" max="10" value={p.energy} onChange={e=>p.setEnergy(+e.target.value)}/></div><div className="field"><label>یادداشت پایان روز</label><textarea value={p.note} onChange={e=>p.setNote(e.target.value)} placeholder="چه چیزی خوب پیش رفت؟"/></div><button className="save" onClick={p.saveDaily}>ذخیره روز</button></aside></div></div>}

function Plan({tasks,goals,date,setDate,setPage}){const upcoming=tasks.filter(t=>t.status!=='done'&&t.status!=='cancelled').slice(0,12);return <div className="content"><div className="hero"><div><div className="eyebrow">MILO / PLAN</div><h1>برنامه‌ریزی</h1><p>کارهای باز و جهت‌های مهمت را یک‌جا ببین.</p></div></div><div className="two-col"><section className="panel"><div className="panel-head"><div><h2>کارهای پیش‌رو</h2><span>{fa(upcoming.length)} کار باز</span></div></div>{upcoming.length?upcoming.map(t=><div className="plan-row" key={t.id}><div><b>{t.title}</b><span>{t.due_date?fmt(t.due_date):'بدون تاریخ'}</span></div><button onClick={()=>{setDate(t.due_date||date);setPage('today')}}>باز کردن</button></div>):<div className="empty">کار بازی وجود ندارد.</div>}</section><section className="panel"><div className="panel-head"><div><h2>اهداف</h2><span>جهت، نه فشار</span></div></div>{goals.length?goals.map(g=><div className="goal-row" key={g.id}><div><b>{g.title}</b><span>{g.description||'بدون توضیح'}</span></div><strong>{fa(g.progress)}٪</strong></div>):<div className="empty">هنوز هدفی ساخته نشده.</div>}</section></div></div>}

function History({tasks}){const days=[...new Set(tasks.map(t=>t.due_date).filter(Boolean))].sort().reverse();return <div className="content"><div className="hero"><div><div className="eyebrow">MILO / HISTORY</div><h1>تاریخچه</h1><p>اثر واقعی اجرا را ببین، نه فقط فهرست کارها.</p></div></div><div className="panel"><div className="history-grid">{days.length?days.map(d=>{const x=tasks.filter(t=>t.due_date===d),done=x.filter(t=>t.status==='done').length;return <div className="history-day" key={d}><div><b>{fmt(d)}</b><span>{fa(done)} از {fa(x.length)} انجام‌شده</span></div><div className="mini-progress"><i style={{width:(x.length?done/x.length*100:0)+'%'}}/></div></div>}):<div className="empty">هنوز تاریخچه‌ای برای نمایش نیست.</div>}</div></div></div>}

function Review({tasks}){const total=tasks.filter(t=>t.status!=='cancelled').length,done=tasks.filter(t=>t.status==='done').length,p=total?Math.round(done/total*100):0;const byArea=areas.map(a=>[a[1],tasks.filter(t=>t.area_id&&false).length]);return <div className="content"><div className="hero"><div><div className="eyebrow">MILO / REVIEW</div><h1>مرور</h1><p>تصمیم‌های بهتر از داده‌های واقعی می‌آیند.</p></div></div><div className="stats"><div><span>کل کارها</span><strong>{fa(total)}</strong></div><div><span>انجام‌شده</span><strong>{fa(done)}</strong></div><div><span>نرخ اجرا</span><strong>{fa(p)}٪</strong></div><div><span>باز</span><strong>{fa(total-done)}</strong></div></div><div className="two-col"><section className="panel"><div className="panel-head"><div><h2>آنچه می‌دانیم</h2><span>بر اساس داده‌های ثبت‌شده</span></div></div><div className="insight"><b>{p>=70?'ریتم اجرا خوب است.':'حجم کار را کمتر و انتخاب‌ها را دقیق‌تر کن.'}</b><p>درصد تکمیل فعلی {fa(p)}٪ است. هدف مرور، پیدا کردن الگوها و حذف اصطکاک است؛ نه قضاوت خودت.</p></div></section><section className="panel"><div className="panel-head"><div><h2>قانون MILO</h2></div></div><p className="principle">کمتر، اما کامل. هر روز چند کار واقعاً مهم را جلو ببر و ظرفیتت را بخشی از برنامه بدان.</p></section></div></div>}

function Settings({user}){return <div className="content"><div className="hero"><div><div className="eyebrow">MILO / SETTINGS</div><h1>تنظیمات</h1><p>حساب و تنظیمات پایه.</p></div></div><section className="panel settings"><div><span>حساب کاربری</span><b>{user.email}</b></div><div><span>منطقه زمانی</span><b>Asia/Tehran</b></div><div><span>ظاهر</span><b>Dark / Premium</b></div><div><span>نسخه</span><b>1.0</b></div></section></div>}

function Root(){const [user,setUser]=useState(null),[ready,setReady]=useState(false);useEffect(()=>{if(!supabase){setReady(true);return}supabase.auth.getSession().then(({data})=>{setUser(data.session?.user||null);setReady(true)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>subscription.unsubscribe()},[]);if(!ready)return <div className="loading-screen">MILO</div>;return user?<App user={user}/>:<Auth onUser={setUser}/>}

createRoot(document.getElementById('root')).render(<Root/>);